import * as api from "../api/api.js";

export const types = {
  COURSE_SEARCH_REQUEST: "COURSE_SEARCH_REQUEST",
  COURSE_SEARCH_SUCCESS: "COURSE_SEARCH_SUCCESS",
  COURSE_SEARCH_ERROR: "COURSE_SEARCH_ERROR",
  COURSE_ADD_REQUEST: "COURSE_ADD_REQUEST",
  COURSE_ADD_SUCCESS: "COURSE_ADD_SUCCESS",
  COURSE_ADD_ERROR: "COURSE_ADD_ERROR",
  COURSE_INIT : "COURSE_INIT"
};

// reducer, create action 구현해야함
